- hosts: all
  gather_facts: no
  become: yes

  vars:
    UserName: tomcat
    JAVA_HOME_PATH: /opt/amazon-corretto-8.462.08.1-linux-x64

  tasks:

    # ===== Corretto (Java) インストール =====
    - name: Download Amazon Corretto
      ansible.builtin.get_url:
        dest: /home/ec2-user/amazon-corretto-8-x64-linux-jdk.tar.gz
        url: https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.tar.gz

    - name: Extract Amazon Corretto
      ansible.builtin.unarchive:
        src: /home/ec2-user/amazon-corretto-8-x64-linux-jdk.tar.gz
        dest: /opt
        remote_src: yes

    - name: Add Corretto to PATH
      ansible.builtin.lineinfile:
        path: /root/.bash_profile
        regexp: '^PATH=.*'
        line: 'PATH=$PATH:$HOME/bin:/opt/amazon-corretto-8.462.08.1-linux-x64/bin'

    # ===== Tomcat インストール =====
    - name: Create tomcat user
      ansible.builtin.user:
        name: '{{ UserName }}'

    - name: Download Tomcat
      ansible.builtin.get_url:
        dest: /home/ec2-user/apache-tomcat-9.0.110.tar.gz
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.110/bin/apache-tomcat-9.0.110.tar.gz

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: /home/ec2-user/apache-tomcat-9.0.110.tar.gz
        dest: /usr/local
        remote_src: yes

    - name: Create symbolic link for tomcat
      ansible.builtin.file:
        src: /usr/local/apache-tomcat-9.0.110
        dest: /usr/local/tomcat
        state: link
        owner: tomcat
        group: tomcat

    - name: Create setenv.sh
      ansible.builtin.copy:
        dest: /usr/local/tomcat/bin/setenv.sh
        content: |
          #!/bin/sh
          CATALINA_HOME=/usr/local/tomcat
          JAVA_HOME={{ JAVA_HOME_PATH }}
          JAVA_OPTS="-Xms128m -Xmx512m"
        mode: '0755'

    - name: Create systemd service for Tomcat
      ansible.builtin.copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat9
          After=network.target

          [Service]
          User=tomcat
          Group=tomcat
          Type=oneshot
          PIDFile=/usr/local/tomcat/tomcat.pid
          RemainAfterExit=yes
          ExecStart=/usr/local/tomcat/bin/startup.sh
          ExecStop=/usr/local/tomcat/bin/shutdown.sh
          ExecReStart=/usr/local/tomcat/bin/shutdown.sh;/usr/local/tomcat/bin/startup.sh

          [Install]
          WantedBy=multi-user.target
        mode: '0755'

    - name: Change ownership and permissions for Tomcat
      ansible.builtin.file:
        path: /usr/local/apache-tomcat-9.0.110
        owner: tomcat
        group: tomcat
        recurse: yes
        mode: '0755'

    - name: Start and enable Tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        state: started
        enabled: yes
        daemon_reload: yes

    # ===== Apache (httpd) インストール =====
    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: Configure Apache reverse proxy
      ansible.builtin.blockinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: EOF
        block: |
          ProxyRequests Off
          ProxyPass        / http://127.0.0.1:8080/
          ProxyPassReverse / http://127.0.0.1:8080/

    - name: Start and enable Apache
      ansible.builtin.systemd:
        name: httpd
        state: restarted
        enabled: yes
        daemon_reload: yes

